added cmake for L476 nucleo and started board specific project
ParadigmBoring/comp1-software pull request #9
Opened 2020-12-03 13:39 UTC by adrwstn

added CMake for L476, under comp1-software/Example-L476/

2020-12-03 14:08 UTC, adrwstn commented
I've added all HAL Drivers to CMake for L456, I figure this is okay (and possibly helpful) for a debug build config and we can remove the redundant ones if we want to set up a leaner build

2020-12-05 16:13 UTC, Burke-Daniel requested changes
Good job on this. One thing we might wanna do is to start populating cubeMX with the peripherals that are configured on the pins in Jasper's schematic, but I'm ok to leave that out for now. Also, I think it it more appropriate for this example to live under `Examples/` as it's own project, instead of in a separate examples folder at the top level.

2020-12-05 16:13 UTC, Burke-Daniel commented on .gitignore
> +cmake-build-debug/
This is what CLion calls the build directory, alright to gitignore it but eventually we will have a script to automate builds, and the folder will be called `build/`. Also add newline to end of file

2020-12-05 16:13 UTC, Burke-Daniel commented on Example-L476/blink476/CMakeLists.txt
> +        # ----END OF LIST-------------------------
Good to remove this, and the two that you have commented out below

2020-12-05 16:13 UTC, Burke-Daniel commented on Example-L476/blink476/Core/Inc/stm32l4xx_hal_conf.h
> +/**
So I don't think we will want to track this in git, see the other Blink project gitignores that live in Src and Inc that ignore these generated files

2020-12-05 16:13 UTC, Burke-Daniel commented on Examples/Blink/CMakeLists.txt
>  cmake_minimum_required(VERSION 3.15.3)
Would remove this from this PR, doesn't pertain to the l476 example

2021-02-14 21:29 UTC, Burke-Daniel commented
@adrwstn have another look at this and lets get this closed out!

2021-06-17 22:39 UTC, closed without merging

2021-06-17 22:41 UTC, adrwstn commented
this is dead (for now)